version: "3.7"

services:
    web:
        image: nginx:latest
        ports:
            - "20221:80"
        volumes:
            - ./:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build: docker/php-fpm
        volumes:
            - ./:/var/www/html
